# Makefile for Transvader, shamelessly edited for use with MinGW

BIN=transvader.exe
OBJ=main.o sprite.o exception.o tv.o
SRC=$(OBJ:%.o=%.cxx)

ALLEG_CXXFLAGS=-lalleg
CXX=g++
CXXFLAGS=-ggdb -Wall 
DEPENDFILE = .depend

all: dep transvader

.PHONY: clean
clean:
	rm -f $(BIN) *.o $(DEPENDFILE)

%.o: %.cxx
	$(CXX) $(CXXFLAGS) -c $<

transvader: $(OBJ) 
	$(CXX) $(OBJ) -o $(BIN) $(ALLEG_CXXFLAGS)


dep: $(SRC)
	$(CXX) -MM $(SRC) > $(DEPENDFILE)

-include $(DEPENDFILE)

