# Polzer/2004

import os;

CCFLAGS = '-O -Wall -Wuninitialized -Wunused'
LINKFLAGS = ''
CPPPATH = '../include'

sources = [Split("""main.cxx
	dragobject.cxx
	editorobject.cxx
	iconviewitem.cxx
	maingui.cxx
	palette.cxx
	preview.cxx""")]


env = Environment( tools = ['default', 'qt'], CCFLAGS = CCFLAGS );
dict = env.Dictionary();

if ( not dict.has_key('QTDIR') ):
	env['QTDIR'] = None 

if ( env['QTDIR'] is None ):	
	print "QTDIR not set, attempting autodetection..."
	qt_locations = [ "/usr/qt", "/usr/qt3", \
		"/usr/lib/qt", "/usr/lib/qt3", \
		"/opt/qt", "/opt/qt3", \
		"/usr/local/qt", "/usr/local/qt3" ]
	for loc in qt_locations:
		print "\tSearching in '" + loc + "'..."
		if ( os.path.exists(loc) ):
			print "\t" + loc + " exists!"
			env["QTDIR"] = loc
			break
# FIXME: qt-mt

if ( os.path.exists ( loc + "/lib/libqt-mt.so" ) ):
	env['QT_LIB'] = "qt-mt"

#print env['TOOLS']
#print env['CPPPATH']
env['CPPPATH'].append(CPPPATH);

env.Program ( 'transvader-editor', sources ) 
